### ISSUE TITLE
Consider transitioning to Dev Container Feature & Dev Container Templates

### ISSUE THREAD

**Issue by eitsupi** [maresb/micromamba-devcontainer#7]
Dev Container Spec is now open and individual features (to install something or to setting something) are intended to be used in combination like Lego blocks, so it is recommended to publish them as Dev Container Features instead of writing them in the Dockerfile.

Also, by publishing Dev Container Templates, users can import templates from the Internet using the devcontainer CLI or VSCode Dev Container.

See below for published Features and Templates.
https://containers.dev/features
https://containers.dev/templates

(The reason I made this post is that I was considering publishing a Dev Container Feature for installing micromamba, on [rocker-org](https://github.com/rocker-org/devcontainer-features), but I thought that if mamba-org is interested in Dev Container it would obviously be more appropriate to be managed here.)

I am familiar with Dev Container Feature and Template publishing and may be able to help if needed.

**Comment by maresb** [comment]
Let's collaborate on this! Thanks for the info, I need to figure out how features work, and I have been thinking lately that this may be due for a total rewrite. I am completely open to suggestions.

**Comment by eitsupi** [comment]
Dev Container Features are packaged shell scripts and container settings.

For example, the devcontainer.json I use to use the devcontainer CLI looks like this:

```json
{
	"image": "mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18",
	"features": {
		"ghcr.io/devcontainers/features/docker-from-docker:1": {
			"version": "latest"
		}
	},
	"remoteUser": "node",
	"postCreateCommand": "npm install -g @devcontainers/cli"
}
```

It will install the docker CLI into the container and mount it to docker.sock, so the users do not need to do anything else to use Docker in the container.

Note that the mount settings for docker.sock are defined below.
https://github.com/devcontainers/features/blob/9366ef7ed18ed63a360d343338bda4ce41e62d09/src/docker-from-docker/devcontainer-feature.json#L44-L50

So users no longer have to do any of the configuration themselves as described in the README here!
https://github.com/mamba-org/micromamba-devcontainer/blob/a49ee3ed76bee607cba81df5785b9db4c2a7e6a6/README.md?plain=1#L62

I think micromamba is small enough and quick enough to install that it is best published as a Dev Container Feature.
For example, users will be able to install micromamba on any container of their choice by specifying the following

```json
{
	"image": "mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18",
	"features": {
		"ghcr.io/mamba-org/devcontainer-features/micromamba:latest": {}
	},
	"remoteUser": "node"
}
```

**Comment by maresb** [comment]
Thanks so much @eitsupi for the explanation!

Am I understanding correctly that this would make the `micromamba` executable available for use within the devcontainer, but not at Dockerfile build time? So if we wanted to use `micromamba` to set up the devcontainer itself, then we must still do something like in this repository?

**Comment by eitsupi** [comment]
> Am I understanding correctly that this would make the `micromamba` executable available for use within the devcontainer, but not at Dockerfile build time? So if we wanted to use `micromamba` to set up the devcontainer itself, then we must still do something like in this repository?

Good point. That's right.
Dev Container Features run as a new stage in the docker build, so Dev Container Features can do all the work that can be done in a Dockerfile, but micromamba cannot be used in user-created Dockefiles because it is installed after the Dockefile's stage.

However, as I have done in the example above (`npm install -g @devcontainers/cli`), there are `postCreateCommand` etc. that is executed immediately after container creation.

**Comment by maresb** [comment]
Ok, great, thanks for the clarification! Since our methods seem to have different use cases, would it make sense to host them in different repos? If you create a personal repo for a micromamba feature, then I think there is a good chance that @wolfv will be able to migrate it to `mamba-org`. Does this make sense?

And for this repo, perhaps it would benefit from removing some of the functionality (like Docker) so that it can be used instead as features? I would really appreciate any advice you could give me in this direction.

**Comment by eitsupi** [comment]
> Since our methods seem to have different use cases, would it make sense to host them in different repos?

If so, Dev Container Templates may be the best choice.
Dev Container Templates is a templating and delivery mechanism for `.devcontainer` directories.
It is a pre-release version of VSCode Dev Container that is It has already been activated.

For example, take a look at the following cpp template.
https://github.com/devcontainers/templates/tree/main/src/cpp

> And for this repo, perhaps it would benefit from removing some of the functionality (like Docker) so that it can be used instead as features?

From what I can see, other than Docker installation, the tools installed on the Dockerfile are the ones covered by [the common-utils feature](https://github.com/devcontainers/features/tree/main/src/common-utils).
It is my belief that the Dev Container Feature has the potential to reduce the amount of management effort for individual users. (It is easy to incorporate upstream updates downstream)

I don't think the pre-commit hook is covered by the existing Features, so many users might benefit from your publishing it as a Dev Container Feature.

**Comment by maresb** [comment]
Thanks @eitsupi for your patience with all my questions! This is all fairly new to me.

I personally have two main use cases for `micromamba` in Docker (maybe there are others which I'm not thinking of):
1. `micromamba` as a CLI tool for user management of Conda environments in interactive sessions such as a devcontainer
2. `micromamba` as a docker-build-time tool to create Conda environments from either `environment.yml` or `conda-lock.yml` (especially advantageous for cases where Python is not necessary)

For 1. I agree that Features are the obvious mechanism. For 2. I may have some remaining confusion. You suggest above using `postCreateCommand` for an install step, but that only executes at container start time. Such install steps are often slow and heavy on bandwidth, so I think it would be nicer at build-time to ensure they run infrequently. (Ideally the install command would be run only when the `conda-lock.yml` changes, and preferably as early as possible to avoid cache-busting.) So I wonder if there are other possible compromises between doing everything by hand like here vs. `postCreateCommand`? For example, would it be possible for the template to make use of a `conda-lock.yml`? 

In other words, do you see Features as able to handle primarily case 1., or could case 2. somehow be covered by Features in a robust manner?

If I were to publish a pre-commit Feature, do you think that this repository could be refactored as a template? Do you think it could be accepted into the official devcontainers/templates repository, or should we aim to maintain that separately?

Finally, I think that this paradigm of stacking various Docker stages like legos has a lot of potential also outside of the strict context of devcontainers. For example, [mamba-org/micromamba-docker](https://github.com/mamba-org/micromamba-docker) prebuilds `micromamba` images on several different base images, and provides [instructions for other images](https://github.com/mamba-org/micromamba-docker#adding-micromamba-to-an-existing-docker-image) as well. If it makes sense, we may be able to refactor micromamba-docker so that both efforts can benefit from each other.

**Comment by eitsupi** [comment]
> For example, would it be possible for the template to make use of a `conda-lock.yml`?

Possible. Please check that the above cpp contains a shell script.

> If I were to publish a pre-commit Feature, do you think that this repository could be refactored as a template? Do you think it could be accepted into the official devcontainers/templates repository, or should we aim to maintain that separately?

My understanding is that it is not directly related to mamba, so it might be better to publish it elsewhere.
devcontainers does not accept new Features and encourages the community, including individuals, to publish Features.

> Finally, I think that this paradigm of stacking various Docker stages like legos has a lot of potential also outside of the strict context of devcontainers. For example, [mamba-org/micromamba-docker](https://github.com/mamba-org/micromamba-docker) prebuilds `micromamba` images on several different base images, and provides [instructions for other images](https://github.com/mamba-org/micromamba-docker#adding-micromamba-to-an-existing-docker-image) as well. If it makes sense, we may be able to refactor micromamba-docker so that both efforts can benefit from each other.

Yes, I think most of what has been written in the Dockerfile can be moved to the Dev Container Feature.
For example, the following two build almost the same container, but you can see that the latter uses the Dev Container Feature, which simplifies the content.
https://github.com/microsoft/vscode-dev-containers/tree/main/containers/r/.devcontainer
https://github.com/rocker-org/devcontainer-images/tree/main/src/r-ver

**Comment by eitsupi** [comment]
Note that with today's release, the VSCode Dev Container extension has implemented the ability to download Dev Container Features and Dev Container Templates.

![image](https://user-images.githubusercontent.com/50911393/199798373-b7938cdb-6708-4839-abc5-6056944a8e83.png)

It would be great if micromamba could be made available here.

**Comment by maresb** [comment]
Yes, I agree! It's been a really busy week for me. In case you haven't started already, I hope to get a start on it this weekend over at https://github.com/mamba-org/micromamba-docker/issues/228.

**Comment by eitsupi** [comment]
I can implement a Feature that installs micromamba in a few hours, but I don't know how to transfer it here.

- Create a new repository of mine (I'll transfer it here later)
- Add it to my Dev Container Feature monorepo (I will copy the source code and create a PR later when another repository is created here)

If you are willing, I can do it one way or the other. (I will use the [Feature Template](https://github.com/devcontainers/feature-template), so the license will be the MIT license)

**Comment by maresb** [comment]
> I can implement a Feature that installs micromamba in a few hours

Excellent!!!

Would you be open to making it in a fork of [mamba-org/micromamba-docker](https://github.com/mamba-org/micromamba-docker)? I think it would be nice to unify both approaches as much as possible.

Otherwise, whatever is the most convenient for you. I don't see any problem with getting started, and then we figure out the details of where it should live later.

I like the MIT license, and so do many others. :slightly_smiling_face:

**Comment by eitsupi** [comment]
> Would you be open to making it in a fork of [mamba-org/micromamba-docker](https://github.com/mamba-org/micromamba-docker)? I think it would be nice to unify both approaches as much as possible.

It is possible to create a fork of that repository, but I don't know how to combine it with existing code; to distribute the Dev Container Feature with devcontainer CLI, we need a directory structure like the one specified on the following page.
https://containers.dev/implementors/features-distribution/

**Comment by maresb** [comment]
> we need a directory structure like...

Yes, ok, that will indeed be awkward to do directly.

In that case, I think it would make more sense to develop the feature in a separate repository. That would give us flexibility to:
- transfer it to mamba-org
- add it later into [mamba-org/micromamba-docker](https://github.com/mamba-org/micromamba-docker) as a submodule

**Comment by eitsupi** [comment]
We can now install micromamba with `devcontainer.json` as follows from this repo https://github.com/eitsupi/mamba-devcontainer-features.

```json
{
	"name": "Debian",
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",
	"remoteUser": "vscode",
	"features": {
		"ghcr.io/eitsupi/mamba-devcontainer-features/micromamba:latest": {}
	}
}
```

However, this alone is not out-of-the-box and needs to be improved to configure the shell and channel settings.

**Comment by maresb** [comment]
Thanks so much for this @eitsupi! I wanted to let you know that I have not forgotten this. This weekend I was busier than expected, and unfortunately couldn't make time to experiment with this.

I am still very eager to test it and figure out how best to manage the activation script and integrate this with micromamba-docker.

**Comment by eitsupi** [comment]
Thanks for letting me know!
I think I implemented the basic part, so I hope you can experiment with the changes as you like. (I will, of course, do a review)

**Comment by maresb** [comment]
Hi @eitsupi, I have a personal question for you. Could you please contact me via services-eitsupi@tensorial.com if you get the chance? (I wasn't able to find your e-mail on the rocker-org website.)
